# Split Tuple
this notebook testing the difficulty of classifying the three labels of Browser, Operation-System, Application (BOA) verses classifying the labels separately.

# Import

In [32]:
import pandas as pd
from pycaret.classification import *
import time

# Settings

In [33]:
# set constants
target_label = ''
learning_model = 'et' #['rf','et','lightgbm','xgboost']
num_features = ['min_packet_size', 'min_fpkt', 'min_bpkt']
file_name = "converted_all_features_"
path = "../Datasets/" + target_label + "_dataset/"
os_prediction = []
browser_prediction = []
app_prediction = []

In [34]:
# function for making model-prediction over the data set and measure the run time 
def timed_prediction(in_data,in_model):
    t = time.process_time()
    predicted = predict_model(in_model, data=in_data)
    elapsed_time = time.process_time() - t
    print("prediction took: " + str(elapsed_time))
    return predicted

In [35]:
# function for checkign the correction of the model-prediction over the data
def check_correction(in_predicted):
    count=0
    index = in_predicted.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
        if str(int(in_predicted.iloc[i][target_label])) != str(int(in_predicted.iloc[i]['Label'])):
            #print("prediction not matched in line " + str(i) + " as " + str(in_predicted.iloc[i]['app']) + "!=" + str(in_predicted.iloc[i]['Label']))
            count=count+1
    print("number of error: " + str(count) + " from " + str(number_of_rows) + " test samples \n which is " + str(100*count/number_of_rows) + " precent of error.")

# OS
read proper data, setup Classifier, Compare Models and Predicte.

In [36]:
target_label = 'os'
path = "../Datasets/" + target_label + "_dataset/"

In [37]:
os_data = pd.read_csv(path+file_name+target_label+'.csv',
                      sep='\t',
                      skiprows=[1])

In [38]:
setup(data=os_data,
      target=target_label,
      silent=True)
model=create_model(learning_model)

In [39]:
predicted = timed_prediction(os_data,model)

prediction took: 1.234375

In [40]:
os_prediction = predicted['Label']

In [41]:
predicted.head() # fix errors counter

,fSSL_session_id_len,fSSL_num_extensions,fSSL_num_compression_methods,SYN_tcp_scale,SYN_MSS,SYN_tcp_winsize,fcipher_suites_1,fcipher_suites_2,fcipher_suites_3,fSSLv_1,...,std_fpkt,std_bpkt,mean_fpkt,mean_bpkt,mean_fttl_1,mean_fttl_2,num_keep_alive,os,Label,Score
0,32,13,1,8,1460,8192,0,1,0,0,...,81.771159,355.893919,71.938138,1289.699861,0,1,2,2,2,1.0
1,0,7,1,8,1460,8192,0,0,1,0,...,307.559344,606.057694,268.333333,611.750000,0,1,0,2,2,1.0
2,0,12,1,8,1460,8192,0,1,0,0,...,98.073770,323.085513,80.223022,1319.186207,0,1,0,2,2,1.0
3,0,12,1,8,1460,8192,0,1,0,0,...,122.320333,321.179295,89.828571,176.085714,0,1,19,2,2,1.0
4,0,7,1,8,1460,8192,0,0,0,0,...,147.162557,678.502510,139.272727,626.900000,0,1,0,2,2,1.0

# Browser
read proper data, setup Classifier, Compare Models and Predicte.

In [42]:
target_label = 'browser'
path = "../Datasets/" + target_label + "_dataset/"

In [43]:
browser_data = pd.read_csv(path+file_name+target_label+'.csv',
                      sep='\t',
                      skiprows=[1])

In [44]:
setup(data=browser_data,
      target=target_label,
      silent=True)
model=create_model(learning_model)

In [45]:
predicted = timed_prediction(browser_data,model)

prediction took: 1.671875

In [46]:
browser_prediction = predicted['Label']
predicted.head() # fix errors counter

,fSSL_session_id_len,fSSL_num_extensions,fSSL_num_compression_methods,SYN_tcp_scale,SYN_MSS,SYN_tcp_winsize,fcipher_suites_1,fcipher_suites_2,fcipher_suites_3,fSSLv_1,...,std_fpkt,std_bpkt,mean_fpkt,mean_bpkt,mean_fttl_1,mean_fttl_2,num_keep_alive,browser,Label,Score
0,32,13,1,8,1460,8192,0,1,0,0,...,81.771159,355.893919,71.938138,1289.699861,0,1,2,100,100,1.0
1,0,7,1,8,1460,8192,0,0,1,0,...,307.559344,606.057694,268.333333,611.750000,0,1,0,600,600,1.0
2,0,12,1,8,1460,8192,0,1,0,0,...,98.073770,323.085513,80.223022,1319.186207,0,1,0,100,100,1.0
3,0,12,1,8,1460,8192,0,1,0,0,...,122.320333,321.179295,89.828571,176.085714,0,1,19,100,100,1.0
4,0,7,1,8,1460,8192,0,0,0,0,...,147.162557,678.502510,139.272727,626.900000,0,1,0,600,600,1.0

# Application
read proper data, setup Classifier, Compare Models and Predicte.

In [47]:
target_label = 'app'
path = "../Datasets/" + target_label + "_dataset/"

In [48]:
app_data = pd.read_csv(path+file_name+target_label+'.csv',
                      sep='\t',
                      skiprows=[1])

In [49]:
setup(data=app_data,
      target=target_label,
      silent=True)
model=create_model(learning_model)

In [50]:
predicted = timed_prediction(app_data,model)

prediction took: 1.796875

In [51]:
app_prediction = predicted['Label']
predicted.head() # fix errors counter

,fSSL_session_id_len,fSSL_num_extensions,fSSL_num_compression_methods,SYN_tcp_scale,SYN_MSS,SYN_tcp_winsize,fcipher_suites_1,fcipher_suites_2,fcipher_suites_3,fSSLv_1,...,std_fpkt,std_bpkt,mean_fpkt,mean_bpkt,mean_fttl_1,mean_fttl_2,num_keep_alive,app,Label,Score
0,32,13,1,8,1460,8192,0,1,0,0,...,81.771159,355.893919,71.938138,1289.699861,0,1,2,6000,6000,1.0
1,0,7,1,8,1460,8192,0,0,1,0,...,307.559344,606.057694,268.333333,611.750000,0,1,0,4000,4000,1.0
2,0,12,1,8,1460,8192,0,1,0,0,...,98.073770,323.085513,80.223022,1319.186207,0,1,0,6000,6000,1.0
3,0,12,1,8,1460,8192,0,1,0,0,...,122.320333,321.179295,89.828571,176.085714,0,1,19,6000,6000,1.0
4,0,7,1,8,1460,8192,0,0,0,0,...,147.162557,678.502510,139.272727,626.900000,0,1,0,5000,5000,1.0

# Compare prediction with original labels

In [56]:
col_len = len(os_data['os'])
os_count = 0
browser_count = 0
app_count = 0
total_count = 0
for i in range(0,col_len):
    if int(os_prediction[i]) != int(os_data['os'][i]):
        total_count=total_count+1
        os_count=os_count+1
        continue
    if int(browser_prediction[i]) != int(browser_data['browser'][i]):
        total_count=total_count+1
        browser_count=browser_count+1
        continue
    if int(app_prediction[i]) != int(app_data['app'][i]):
        total_count=total_count+1
        app_count=app_count+1
        continue
print("total error count = " + str(total_count))
print("it is " + str(100*total_count/col_len) + "% of the data")
print("error in os = " + str(os_count))
print("error in browser = " + str(browser_count))
print("error in app = " + str(app_count))

total error count = 143
it is 0.6930981000387747% of the data
error in os = 0
error in browser = 40
error in app = 103

# whole TUPLE
read proper data, setup Classifier, Compare Models and Predicte.

In [21]:
target_label = 'tuple'
path = "../Datasets/" + target_label + "_dataset/"

In [22]:
data = pd.read_csv(path+file_name+target_label+'.csv',
                      sep='\t',
                      skiprows=[1])

In [23]:
data[target_label].unique()

array([16102, 14602, 15602, 18102, 13102, 11602, 16201, 13201, 18201,
       16101, 13101, 18101, 16202, 18202, 13202, 16302, 18302, 13302,
       13403, 18403, 17403, 14601, 17101, 12101, 17201, 12201, 16403,
       16103, 13103, 18103], dtype=int64)

In [24]:
setup(data=data,
      target=target_label,
      silent=True)
model=create_model(learning_model)

In [25]:
predicted = timed_prediction(data,model)

prediction took: 3.015625

In [26]:
check_correction(predicted)

number of error: 127 from 20632 test samples
 which is 0.6155486622721985 precent of error.